name: TerminatorNPC
version: ${project.version}
main: me.swipez.terminatornpc.TerminatorNPC
api-version: 1.16
authors: [ notnotnotswipez ]
depend: [Citizens]
commands:
  terminator:
    usage: /terminator <subcommand>
    description: Basic commands for all terminator-related things
    permission: terminatornpc.help
permissions:
  terminatornpc.help: { default: op }
  terminatornpc.ignore: { default: op }
  terminatornpc.spawnterminator: { default: op }
  terminatornpc.deleteterminator: { default: op }
  terminatornpc.loadout: { default: op }

  terminatornpc.*:
    default: op
    children:
      terminatornpc.help: true
      terminatornpc.ignore: true
      terminatornpc.spawnterminator: true
      terminatornpc.deleteterminator: true
      terminatornpc.loadout: true
